import 'package:flutter/material.dart';
import '../../../core/constants/app_colors.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms & Conditions'),
        backgroundColor: Colors.transparent,
      ),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          _section(
            isDark,
            'Acceptance of Terms',
            'By downloading, installing, or using this application, you agree to be '
                'bound by these Terms & Conditions. If you do not agree, do not use '
                'the application.',
          ),
          _section(
            isDark,
            'User Responsibility',
            'You are solely responsible for any content you generate, share, or '
                'distribute using this application. The developers assume no liability '
                'for outputs produced by the AI models. Use this application in '
                'compliance with all applicable laws and regulations.',
          ),
          _section(
            isDark,
            'User Conduct',
            'You agree not to use this application to:\n'
                '- Generate illegal content or content that violates any applicable law\n'
                '- Harass, abuse, or harm others through generated content\n'
                '- Distribute generated content in a manner that violates third-party rights\n'
                '- Attempt to reverse engineer, modify, or exploit the application beyond its intended use',
          ),
          _section(
            isDark,
            'No Warranty',
            'This application is provided "as is" without warranty of any kind, express '
                'or implied. The developers do not guarantee that the application will '
                'be error-free, secure, or uninterrupted, or that AI outputs will be '
                'accurate, appropriate, or suitable for any purpose.',
          ),
          _section(
            isDark,
            'Limitation of Liability',
            'Under no circumstances shall the developers be liable for any damages '
                'arising from the use or inability to use this application, including '
                'but not limited to damages for loss of data, content generated by the AI, '
                'or any other loss, even if advised of the possibility of such damages.',
          ),
          _section(
            isDark,
            'Intellectual Property',
            'The application code, design, and branding are the property of the '
                'developers. The GGUF model files are subject to their respective '
                'licenses from their creators. Generated content belongs to the user '
                'who created it.',
          ),
          _section(
            isDark,
            'Modifications to Terms',
            'We reserve the right to modify these terms at any time. Continued use '
                'of the application after changes constitutes acceptance of the new terms. '
                'It is your responsibility to review these terms periodically.',
          ),
          const SizedBox(height: 40),
        ],
      ),
    );
  }

  Widget _section(bool isDark, String title, String body) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: isDark ? AppColors.darkTextPrimary : AppColors.lightTextPrimary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            body,
            style: TextStyle(
              fontSize: 14,
              height: 1.6,
              color: isDark ? AppColors.darkTextSecondary : AppColors.lightTextSecondary,
            ),
          ),
        ],
      ),
    );
  }
}
