import 'package:flutter/material.dart';
import '../../../core/widgets/legal_section.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Terms & Conditions'), backgroundColor: Colors.transparent),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          const LegalSection(title: 'Acceptance of Terms',
              body: 'By downloading, installing, or using this application, you agree to be '
                  'bound by these Terms & Conditions. If you do not agree, do not use the application.'),
          const LegalSection(title: 'User Responsibility',
              body: 'You are solely responsible for any content you generate, share, or '
                  'distribute using this application. The developers assume no liability '
                  'for outputs produced by the AI models. Use this application in '
                  'compliance with all applicable laws and regulations.'),
          const LegalSection(title: 'User Conduct',
              body: 'You agree not to use this application to:\n'
                  '- Generate illegal content or content that violates any applicable law\n'
                  '- Harass, abuse, or harm others through generated content\n'
                  '- Distribute generated content in a manner that violates third-party rights\n'
                  '- Attempt to reverse engineer, modify, or exploit the application beyond its intended use'),
          const LegalSection(title: 'No Warranty',
              body: 'This application is provided "as is" without warranty of any kind, express '
                  'or implied. The developers do not guarantee that the application will '
                  'be error-free, secure, or uninterrupted, or that AI outputs will be '
                  'accurate, appropriate, or suitable for any purpose.'),
          const LegalSection(title: 'Limitation of Liability',
              body: 'Under no circumstances shall the developers be liable for any damages '
                  'arising from the use or inability to use this application, including '
                  'but not limited to damages for loss of data, content generated by the AI, '
                  'or any other loss, even if advised of the possibility of such damages.'),
          const LegalSection(title: 'Intellectual Property',
              body: 'The application code, design, and branding are the property of the '
                  'developers. The GGUF model files are subject to their respective '
                  'licenses from their creators. Generated content belongs to the user who created it.'),
          const LegalSection(title: 'Modifications to Terms',
              body: 'We reserve the right to modify these terms at any time. Continued use '
                  'of the application after changes constitutes acceptance of the new terms. '
                  'It is your responsibility to review these terms periodically.'),
          const SizedBox(height: 40),
        ],
      ),
    );
  }
}
