class ApiEndpoints {
  ApiEndpoints._();

  static const List<Map<String, dynamic>> localModelsCatalog = [
    // ── Ultra Tiny (<100 MB) ──
    {
      'id': 'smollm_135m_q2',
      'name': 'SmolLM2 (135M Q2)',
      'sizeGb': 0.085,
      'params': '135M',
      'minRamRequired': 0.8,
      'tier': 3,
      'description':
          'Extreme lightweight model optimized for very low-end Android devices.',
      'downloadUrl':
          'https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct-GGUF/resolve/main/SmolLM2-135M-Instruct-Q2_K.gguf',
      'architecture': 'gguf',
      'quantization': 'Q2_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 2,
      'recommendedStorageFreeGb': 1,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'smollm_135m_iq3',
      'name': 'SmolLM2 (135M IQ3)',
      'sizeGb': 0.086,
      'params': '135M',
      'minRamRequired': 0.8,
      'tier': 3,
      'description':
          'Ultra compressed reasoning capable model for entry Android phones.',
      'downloadUrl':
          'https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct-GGUF/resolve/main/SmolLM2-135M-Instruct-IQ3_M.gguf',
      'architecture': 'gguf',
      'quantization': 'IQ3_M',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 2,
      'recommendedStorageFreeGb': 1,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    // ── Tiny (<200 MB) ──
    {
      'id': 'smollm_360m_q2',
      'name': 'SmolLM2 (360M Q2)',
      'sizeGb': 0.18,
      'params': '360M',
      'minRamRequired': 1.0,
      'tier': 3,
      'description':
          'Tiny conversational model suitable for budget Android hardware.',
      'downloadUrl':
          'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q2_K.gguf',
      'architecture': 'gguf',
      'quantization': 'Q2_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 3,
      'recommendedStorageFreeGb': 1,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'smollm_360m_q3',
      'name': 'SmolLM2 (360M Q3)',
      'sizeGb': 0.20,
      'params': '360M',
      'minRamRequired': 1.2,
      'tier': 3,
      'description':
          'Better quality than Q2 while remaining tiny.',
      'downloadUrl':
          'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q3_K_M.gguf',
      'architecture': 'gguf',
      'quantization': 'Q3_K_M',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 3,
      'recommendedStorageFreeGb': 1,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'tinyllama_1_1b_q2',
      'name': 'TinyLlama (1.1B Q2)',
      'sizeGb': 0.52,
      'params': '1.1B',
      'minRamRequired': 1.8,
      'tier': 3,
      'description':
          'Small Android friendly model with good conversational performance.',
      'downloadUrl':
          'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q2_K.gguf',
      'architecture': 'gguf',
      'quantization': 'Q2_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 5,
      'recommendedStorageFreeGb': 2,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'smollm_135m_q4',
      'name': 'SmolLM2 (135M Q4)',
      'sizeGb': 0.10,
      'params': '135M',
      'minRamRequired': 1.0,
      'tier': 3,
      'description': 'Ultra-lightweight model for extreme low-end hardware. Near-instant responses with minimal battery draw.',
      'downloadUrl': 'https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct-GGUF/resolve/main/SmolLM2-135M-Instruct-Q4_K_M.gguf',
      'architecture': 'gguf',
      'quantization': 'Q4_K_M',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 2,
      'recommendedStorageFreeGb': 1,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'smollm_360m_q4',
      'name': 'SmolLM2 (360M Q4)',
      'sizeGb': 0.25,
      'params': '360M',
      'minRamRequired': 1.2,
      'tier': 3,
      'description': 'Small but capable model for constrained hardware. Good conversational ability in a ~250 MB footprint.',
      'downloadUrl': 'https://huggingface.co/bartowski/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q4_K_M.gguf',
      'architecture': 'gguf',
      'quantization': 'Q4_K_M',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 3,
      'recommendedStorageFreeGb': 1,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'qwen_0_5b_q2',
      'name': 'Qwen 0.5B (Q2 quantized)',
      'sizeGb': 0.20,
      'params': '0.5B',
      'minRamRequired': 1.2,
      'tier': 3,
      'description': 'Aggressively compressed 0.5B model. Tiny footprint while retaining useful conversational ability for constrained hardware.',
      'downloadUrl': 'https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat-GGUF/resolve/main/qwen1_5-0_5b-chat-q2_k.gguf',
      'architecture': 'gguf',
      'quantization': 'Q2_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 3,
      'recommendedStorageFreeGb': 1,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    // ── Small (~300-500 MB) ──
    {
      'id': 'qwen_0_5b_q4',
      'name': 'Qwen 0.5B (Q4)',
      'sizeGb': 0.35,
      'params': '0.5B',
      'minRamRequired': 2.0,
      'tier': 3,
      'description': 'Compact 0.5B model optimized for fast responses on low-end hardware. Good balance of speed and quality.',
      'downloadUrl': 'https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat-GGUF/resolve/main/qwen1_5-0_5b-chat-q4_0.gguf',
      'architecture': 'gguf',
      'quantization': 'Q4_0',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 3,
      'recommendedStorageFreeGb': 2,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'phi_1_5_q2',
      'name': 'Phi-1.5 (1.3B Q2)',
      'sizeGb': 0.54,
      'params': '1.3B',
      'minRamRequired': 1.8,
      'tier': 3,
      'description': 'Microsoft Phi-1.5 aggressively quantized. Strong reasoning for its size. Great for constrained devices needing smarter responses.',
      'downloadUrl': 'https://huggingface.co/tensorblock/phi-1_5-GGUF/resolve/main/phi-1_5-Q2_K.gguf',
      'architecture': 'gguf',
      'quantization': 'Q2_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'low_end',
      'batteryImpact': 'low',
      'estimatedLoadSeconds': 5,
      'recommendedStorageFreeGb': 2,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    // ── Mid-range ──
    {
      'id': 'gemma_2_2b_q2',
      'name': 'Gemma-2B (Q2)',
      'sizeGb': 0.90,
      'params': '2B',
      'minRamRequired': 2.5,
      'tier': 2,
      'description': 'Google Gemma 2B optimized for on-device mobile inference. Strong reasoning with modest RAM requirements.',
      'downloadUrl': 'https://huggingface.co/google/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q2_K.gguf',
      'architecture': 'gguf',
      'quantization': 'Q2_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'mid_range',
      'batteryImpact': 'medium',
      'estimatedLoadSeconds': 8,
      'recommendedStorageFreeGb': 3,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'phi_2_q2',
      'name': 'Phi-2 (2.7B Q2)',
      'sizeGb': 1.10,
      'params': '2.7B',
      'minRamRequired': 3.0,
      'tier': 2,
      'description': 'Microsoft Phi-2 compressed to 1.1 GB. Excellent code/reasoning ability for a mid-range mobile footprint.',
      'downloadUrl': 'https://huggingface.co/TheBloke/phi-2-GGUF/resolve/main/phi-2.Q2_K.gguf',
      'architecture': 'gguf',
      'quantization': 'Q2_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'mid_range',
      'batteryImpact': 'medium',
      'estimatedLoadSeconds': 10,
      'recommendedStorageFreeGb': 4,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'gemma_2_2b_q4',
      'name': 'Gemma-2B (Q4)',
      'sizeGb': 1.50,
      'params': '2B',
      'minRamRequired': 3.5,
      'tier': 2,
      'description': 'Google Gemma 2B with higher precision. Best quality-per-byte for mobile-ready on-device intelligence.',
      'downloadUrl': 'https://huggingface.co/google/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf',
      'architecture': 'gguf',
      'quantization': 'Q4_K_M',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'mid_range',
      'batteryImpact': 'medium',
      'estimatedLoadSeconds': 10,
      'recommendedStorageFreeGb': 4,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'llama_3_3b_q4',
      'name': 'Llama 3.2 (3B Q4)',
      'sizeGb': 1.95,
      'params': '3B',
      'minRamRequired': 4.0,
      'tier': 2,
      'description': 'Meta Llama 3.2 3B — balanced model offering robust language reasoning and conversational nuance. Standard mid-range device compute.',
      'downloadUrl': 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf',
      'architecture': 'gguf',
      'quantization': 'Q4_K_M',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'mid_range',
      'batteryImpact': 'medium',
      'estimatedLoadSeconds': 12,
      'recommendedStorageFreeGb': 5,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    {
      'id': 'phi_3_mini_q4',
      'name': 'Phi-3 Mini (3.8B Q4)',
      'sizeGb': 2.20,
      'params': '3.8B',
      'minRamRequired': 4.5,
      'tier': 2,
      'description': 'Microsoft Phi-3 Mini. State-of-the-art small language model with strong reasoning and instruction following.',
      'downloadUrl': 'https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf',
      'architecture': 'gguf',
      'quantization': 'Q4_K',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'mid_range',
      'batteryImpact': 'medium',
      'estimatedLoadSeconds': 12,
      'recommendedStorageFreeGb': 5,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
    // ── High-end ──
    {
      'id': 'mistral_7b_q4',
      'name': 'Mistral (7B Q4)',
      'sizeGb': 4.1,
      'params': '7B',
      'minRamRequired': 8.0,
      'tier': 1,
      'description': 'High-fidelity model for advanced code writing and long-context reasoning. For high-tier hardware.',
      'downloadUrl': 'https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf',
      'architecture': 'gguf',
      'quantization': 'Q4_K_M',
      'supportsVision': false,
      'supportsToolCalling': false,
      'supportsMultimodal': false,
      'priorityTier': 'high_end',
      'batteryImpact': 'high',
      'estimatedLoadSeconds': 20,
      'recommendedStorageFreeGb': 10,
      'minAndroidSdk': 26,
      'preferredDelegate': 'gpu',
      'supportsBackgroundInference': true,
    },
  ];
}
